# Generated by Django 3.2.5 on 2023-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basededonnees',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='basededonnees',
            name='taille_fichier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
