# Generated by Django 3.2.5 on 2023-12-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSpecialCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteres_speciaux', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='metacolonne',
            name='meta_special_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_colonne', to='DataGuardianApp.metaspecialcar'),
        ),
    ]
