# Generated by Django 3.2.5 on 2023-12-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='parametre_diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='DataGuardianApp.critere'),
        ),
    ]
