# Generated by Django 3.2.5 on 2023-12-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSpecialCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteres_speciaux', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='basededonnees',
            old_name='Projet',
            new_name='projet',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='metacolonne',
            name='dependances',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metaanomalie',
            name='valeur_trouvee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacolonne',
            name='meta_special_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_colonne', to='DataGuardianApp.metaspecialcar'),
        ),
    ]
