# Generated by Django 3.2.5 on 2023-12-08 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0002_auto_20231204_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(default=datetime.datetime.now)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='DataGuardianApp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='basededonnees',
            name='Projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_de_donnees', to='DataGuardianApp.projet'),
        ),
    ]
