# Generated by Django 3.2.5 on 2023-11-25 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0002_auto_20231123_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basededonnees',
            name='fichier_bd',
            field=models.FileField(upload_to='uploaded_db/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'sql', 'txt', 'json', 'xml'])]),
        ),
    ]
