# Generated by Django 3.2.5 on 2023-12-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0003_alter_metaanomalie_valeur_trouvee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='utilisateur',
        ),
    ]
