# Generated by Django 3.2.5 on 2023-12-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0004_remove_diagnostic_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacolonne',
            name='dependances',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
