# Generated by Django 3.2.5 on 2023-12-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataGuardianApp', '0005_metacolonne_dependances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basededonnees',
            old_name='Projet',
            new_name='projet',
        ),
    ]
